name: Build

on:
  pull_request:
    branches:
      - '*'  # Trigger build when pushing to the main branch
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure this matches your local Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build the App
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build

      - name: install firebase tools
        run: npm install -g firebase-tools

      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUQ123_4846B }}
          projectId: buq123-4846b
          channelId: 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'